[tool.mypy]
strict = true
allow_subclassing_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = false
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
namespace_packages = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = ["statsmodels.tsa.api", "statsmodels.tsa.statespace.sarimax"]
ignore_missing_imports = true

[tool.ruff]
select = ["E", "F", "I", "N", "ANN", "S", "B", "A", "COM", "C4", "DTZ", "ISC", "ICN", "G",
    "PIE", "PYI", "RET", "SLF", "SIM", "ARG", "PTH", "PLE", "PLC", "PLW", "FLY", "RUF"]
ignore = [
    "ANN101", # missing-type-self
    "ANN401", # any-type
    "S101", # assert
    "S311", # suspicious-non-cryptographic-random-usage
    "SIM108", # if-else-block-instead-of-if-exp
    "COM812", # misisng-trailing-comma
    "PLW2901", # redefiend-loop-name
    "RET504", # unnecessary-assign
]
unfixable = [
    "F841", # unused-variable
]
line-length = 120

[tool.ruff.isort]
force-single-line = true

[tool.black]
line-length = 120
exclude = "scripts"

[tool.ariadne-codegen]
# ariadne-codegen
queries_path = "custom_components/solar_battery_forecast/octopus_api/queries.graphql"
remote_schema_url = "https://api.octopus.energy/v1/graphql/"
target_package_path = "custom_components/solar_battery_forecast/octopus_api"
plugins = ["ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin"]
