# Generated by ariadne-codegen on 2024-03-01 12:15
# Source: custom_components/solar_battery_forecast/octopus_api/queries.graphql

from typing import Optional

from .account_query import AccountQuery, AccountQueryAccount
from .async_base_client import AsyncBaseClient
from .authenticate import Authenticate, AuthenticateObtainKrakenToken
from .saving_sessions_query import (
    SavingSessionsQuery,
    SavingSessionsQuerySavingSessions,
)


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def authenticate(
        self, api_key: str
    ) -> Optional[AuthenticateObtainKrakenToken]:
        query = gql(
            """
            mutation Authenticate($apiKey: String!) {
              obtainKrakenToken(input: {APIKey: $apiKey}) {
                token
              }
            }
            """
        )
        variables: dict[str, object] = {"apiKey": api_key}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return Authenticate.parse_obj(data).obtain_kraken_token

    async def account_query(self, account_number: str) -> Optional[AccountQueryAccount]:
        query = gql(
            """
            query AccountQuery($accountNumber: String!) {
              account(accountNumber: $accountNumber) {
                electricityAgreements(active: true) {
                  tariff {
                    __typename
                    ... on HalfHourlyTariff {
                      id
                      unitRates {
                        value
                        validTo
                        validFrom
                      }
                    }
                  }
                  meterPoint {
                    meters {
                      meterType
                      smartExportElectricityMeter {
                        deviceId
                      }
                      smartImportElectricityMeter {
                        deviceId
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"accountNumber": account_number}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return AccountQuery.parse_obj(data).account

    async def saving_sessions_query(
        self, account_number: str
    ) -> Optional[SavingSessionsQuerySavingSessions]:
        query = gql(
            """
            query SavingSessionsQuery($accountNumber: String!) {
              savingSessions {
                events(getDevEvents: false) {
                  id
                  startAt
                  endAt
                  rewardPerKwhInOctoPoints
                }
                account(accountNumber: $accountNumber) {
                  hasJoinedCampaign
                  joinedEvents {
                    eventId
                    startAt
                    endAt
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"accountNumber": account_number}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return SavingSessionsQuery.parse_obj(data).saving_sessions
