# Generated by ariadne-codegen
# Source: custom_components/solar_battery_forecast/octopus_api/queries.graphql

from typing import Any, Optional

from .account_query import AccountQuery, AccountQueryAccount
from .async_base_client import AsyncBaseClient
from .authenticate import Authenticate, AuthenticateObtainKrakenToken


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def authenticate(
        self, api_key: str, **kwargs: Any
    ) -> Optional[AuthenticateObtainKrakenToken]:
        query = gql("""
            mutation Authenticate($apiKey: String!) {
              obtainKrakenToken(input: {APIKey: $apiKey}) {
                token
              }
            }
            """)
        variables: dict[str, object] = {"apiKey": api_key}
        response = await self.execute(
            query=query, operation_name="Authenticate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Authenticate.model_validate(data).obtain_kraken_token

    async def account_query(
        self, account_number: str, **kwargs: Any
    ) -> Optional[AccountQueryAccount]:
        query = gql("""
            query AccountQuery($accountNumber: String!) {
              account(accountNumber: $accountNumber) {
                electricityAgreements(active: true) {
                  tariff {
                    __typename
                    ... on HalfHourlyTariff {
                      id
                      unitRates {
                        value
                        validTo
                        validFrom
                      }
                    }
                  }
                  meterPoint {
                    meters {
                      meterType
                      smartExportElectricityMeter {
                        deviceId
                      }
                      smartImportElectricityMeter {
                        deviceId
                      }
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"accountNumber": account_number}
        response = await self.execute(
            query=query, operation_name="AccountQuery", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AccountQuery.model_validate(data).account
