#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

mkdir -p /config/custom_components && touch /config/custom_components/__init__.py

# Set the path to custom_components
export PYTHONPATH="/config/custom_components"

# Start Home Assistant
hass --config /config --debug
